// DashboardPage/index.tsx
import type { FC } from 'react';
import { useDashboardPage } from './useDashboardPage';
import { DashboardPageView } from './DashboardPage.view';

const DashboardPage: FC = () => {
  const {
    isSidebarOpen,
    selectedTask,
    isConfirmModalOpen,
    isConfirmLoading,
    isReviewMenuOpen,
    isTaskCreationModalOpen,
    isTaskCreationConfirmOpen,
    isTaskReviewAiChooserOpen,
    selectedReviewCardId,
    selectedReviewCard,
    isReviewResultModalOpen,
    selectedResultReviewCardId,
    backlogCards,
    completedCards,
    reviewCardsLoading,
    reviewCardsError,
    categories,
    isLoadingCategories,
    categoryError,
    backlogFilterCategoryId,
    backlogSortBy,
    setBacklogFilterCategoryId,
    setBacklogSortBy,
    completedFilterCategoryId,
    completedSortBy,
    setCompletedFilterCategoryId,
    setCompletedSortBy,
    openConfirmModal,
    closeConfirmModal,
    openReviewMenu,
    closeReviewMenu,
    closeTaskCreationModal,
    handleTaskCreationBackgroundClick,
    handleConfirmTaskCreationClose,
    handleCancelTaskCreationClose,
    openTaskReviewAiChooser,
    closeTaskReviewAiChooser,
    openReviewResultModal,
    closeReviewResultModal,
    handleReviewCardDeleteSuccess,
    isExamSheetModalOpen,
    openExamSheetModal,
    closeExamSheetModal,
    isReviewCardSettingsModalOpen,
    selectedSettingsReviewCardId,
    openReviewCardSettingsModal,
    closeReviewCardSettingsModal,
    handleSaveReviewCardSettings,
    handleSaveCategory,
    handleCreateTask,
    toggleSidebar,
    selectedTaskType,
    setSelectedTaskType,
    taskField,
    handleTaskFieldChange,
    handleConfirmTask,
    isChatModalOpen,
    closeChatModal,
    handleChatQuestionsGenerated,
    isChatCloseConfirmOpen,
    handleChatBackgroundClick,
    handleConfirmChatClose,
    handleCancelChatClose,
    handleRetryFetch,
    isReviewTestChatModalOpen,
    closeReviewTestChatModal,
    reviewTestTutorLevel,
  } = useDashboardPage();

  return (
    <DashboardPageView
      isSidebarOpen={isSidebarOpen}
      onToggleSidebar={toggleSidebar}
      selectedTask={selectedTask}
      isConfirmModalOpen={isConfirmModalOpen}
      isConfirmLoading={isConfirmLoading}
      isReviewMenuOpen={isReviewMenuOpen}
      isTaskCreationModalOpen={isTaskCreationModalOpen}
      isTaskCreationConfirmOpen={isTaskCreationConfirmOpen}
      isTaskReviewAiChooserOpen={isTaskReviewAiChooserOpen}
      selectedReviewCardId={selectedReviewCardId}
      selectedReviewCard={selectedReviewCard}
      backlogCards={backlogCards}
      completedCards={completedCards}
      reviewCardsLoading={reviewCardsLoading}
      reviewCardsError={reviewCardsError}
      categories={categories}
      isLoadingCategories={isLoadingCategories}
      categoryError={categoryError}
      backlogFilterCategoryId={backlogFilterCategoryId}
      backlogSortBy={backlogSortBy}
      onBacklogFilterCategoryChange={setBacklogFilterCategoryId}
      onBacklogSortChange={setBacklogSortBy}
      completedFilterCategoryId={completedFilterCategoryId}
      completedSortBy={completedSortBy}
      onCompletedFilterCategoryChange={setCompletedFilterCategoryId}
      onCompletedSortChange={setCompletedSortBy}
      onOpenConfirmModal={openConfirmModal}
      onCloseConfirmModal={closeConfirmModal}
      onOpenReviewMenu={openReviewMenu}
      onCloseReviewMenu={closeReviewMenu}
      onCloseTaskCreationModal={closeTaskCreationModal}
      onTaskCreationBackgroundClick={handleTaskCreationBackgroundClick}
      onConfirmTaskCreationClose={handleConfirmTaskCreationClose}
      onCancelTaskCreationClose={handleCancelTaskCreationClose}
      onOpenTaskReviewAiChooser={openTaskReviewAiChooser}
      onCloseTaskReviewAiChooser={closeTaskReviewAiChooser}
      isReviewResultModalOpen={isReviewResultModalOpen}
      selectedResultReviewCardId={selectedResultReviewCardId}
      onOpenReviewResultModal={openReviewResultModal}
      onCloseReviewResultModal={closeReviewResultModal}
      onReviewCardDeleteSuccess={handleReviewCardDeleteSuccess}
      isExamSheetModalOpen={isExamSheetModalOpen}
      onOpenExamSheetModal={openExamSheetModal}
      onCloseExamSheetModal={closeExamSheetModal}
      isReviewCardSettingsModalOpen={isReviewCardSettingsModalOpen}
      selectedSettingsReviewCardId={selectedSettingsReviewCardId}
      onOpenReviewCardSettingsModal={openReviewCardSettingsModal}
      onCloseReviewCardSettingsModal={closeReviewCardSettingsModal}
      onSaveReviewCardSettings={handleSaveReviewCardSettings}
      onSaveCategory={handleSaveCategory}
      onCreateTask={handleCreateTask}
      selectedTaskType={selectedTaskType}
      onSelectTaskType={setSelectedTaskType}
      taskField={taskField}
      onTaskFieldChange={handleTaskFieldChange}
      onConfirmTask={handleConfirmTask}
      isChatModalOpen={isChatModalOpen}
      onCloseChatModal={closeChatModal}
      onChatQuestionsGenerated={handleChatQuestionsGenerated}
      isChatCloseConfirmOpen={isChatCloseConfirmOpen}
      onChatBackgroundClick={handleChatBackgroundClick}
      onConfirmChatClose={handleConfirmChatClose}
      onCancelChatClose={handleCancelChatClose}
      onRetryFetch={handleRetryFetch}
      isReviewTestChatModalOpen={isReviewTestChatModalOpen}
      onCloseReviewTestChatModal={closeReviewTestChatModal}
      reviewTestTutorLevel={reviewTestTutorLevel}
    />
  );
};

export default DashboardPage;