spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/algornote?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:4592}

app:
  frontend:
    landing-url: http://localhost:5174  # Development landing page URL
    dashboard-url: http://localhost:5173/dashboard  # Development dashboard URL

revalidation:
  schedule: "*/10 * * * * *"  # 개발 환경: 10초마다 실행
