spring:
  config:
    activate:
      on-profile: dev

app:
  frontend:
    landing-url: http://localhost:5174  # Development landing page URL
    dashboard-url: http://localhost:5173/dashboard  # Development dashboard URL

revalidation:
  schedule: "*/10 * * * * *"  # 개발 환경: 10초마다 실행
