spring:
  config:
    activate:
      on-profile: prod
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 31536000 # 1 year cache for static resources

revalidation:
  schedule: 0 0 * * * *  # 배포 환경: 매시간 정각
