spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/algornote?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 31536000

app:
  frontend:
    landing-url: http://localhost:80
    dashboard-url: http://localhost:80/dashboard

revalidation:
  schedule: 0 0 * * * *

